### ISSUE TITLE
Error when reaching short break (org.freedesktop.Notifications.Error.ExcessNotificationGeneration)

### ISSUE THREAD

**Issue by kofm** [zer0-x/ianny#2]
Hi, and thanks for creating this package. With RSIBreak broken on Wayland, this is more than helpful!

Ianny starts correctly but stops when it reaches the short break.
I get the following error when trying to run ianny. 

```
$ RUST_BACKTRACE=full ianny
Application locale: en_US.UTF-8
Binded to org_kde_kwin_idle
Read config from: /home/kofm/.config/io.github.zefr0x.ianny/config.toml
Config: Timer { idle_timeout: 12, short_break_timeout: 12, long_break_timeout: 38, short_break_duration: 10, long_break_duration: 20 }
Short break starts
thread '<unnamed>' panicked at /home/kofm/.local/src/ianny/build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/notify-rust-4.9.0/src/xdg/dbus_rs.rs:113:14:
called `Result::unwrap()` on an `Err` value: Error { kind: Dbus(D-Bus error: Created too many similar notifications in quick succession (org.freedesktop.Notifications.Error.ExcessNotificationGeneration)) }
stack backtrace:
   0:     0x558ea066214f - <unknown>
   1:     0x558ea061626c - <unknown>
   2:     0x558ea0635fdc - <unknown>
   3:     0x558ea06638df - <unknown>
   4:     0x558ea06634c3 - <unknown>
   5:     0x558ea06644cb - <unknown>
   6:     0x558ea0663fa2 - <unknown>
   7:     0x558ea0663f06 - <unknown>
   8:     0x558ea0663ef1 - <unknown>
   9:     0x558ea05fa882 - <unknown>
  10:     0x558ea05fad32 - <unknown>
  11:     0x558ea0610ad6 - <unknown>
  12:     0x558ea06050f6 - <unknown>
  13:     0x558ea0605c63 - <unknown>
  14:     0x558ea0665145 - <unknown>
  15:     0x7f03b1965947 - start_thread
  16:     0x7f03b19eb860 - __clone3
  17:                0x0 - <unknown>
zsh: IOT instruction (core dumped)  RUST_BACKTRACE=full ianny
```

Let me know if I can provide any additional info

**Comment by zefr0x** [comment]
It's an error sent from the Notification Daemon that you use.

It occurs after updating the notification multiple times quickly in a short period to increment the progress bar:
> Error { kind: Dbus(D-Bus error: Created too many similar notifications in quick succession (org.freedesktop.Notifications.Error.ExcessNotificationGeneration)) }
stack backtrace:

Recently the time unit was changed from minutes to seconds, I think that you didn't update your old config file.

> https://github.com/zefr0x/ianny/blob/main/CHANGELOG.md#010alpha2

Sorry. Don't expect breaking changes like this in the future, the next release of Ianny will be a stable one.

I appreciate that Ianny was helpful for you.

**Comment by kofm** [comment]
Hey, thank you very much for the fast response!

I understand, however, I get the same result if I delete my config file and run with the defaults:
```
Application locale: en_US.UTF-8
Binded to org_kde_kwin_idle
Config: Timer { idle_timeout: 240, short_break_timeout: 1200, long_break_timeout: 3840, short_break_duration: 120, long_break_duration: 240 }
Short break starts
thread '<unnamed>' panicked at /home/kofm/.local/src/ianny/build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/notify-rust-4.9.0/src/xdg/dbus_rs.rs:113:14:
called `Result::unwrap()` on an `Err` value: Error { kind: Dbus(D-Bus error: Created too many similar notifications in quick succession (org.freedesktop.Notifications.Error.ExcessNotificationGeneration)) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: IOT instruction (core dumped)  ianny
```

**Comment by zefr0x** [comment]
Could you please provide what Notification Daemon you are using? Are you using KDE, GNOME, mint, or a stand-alone one?

**Comment by kofm** [comment]
Operating System: Fedora Linux 38
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.11
Kernel Version: 6.5.9-200.fc38.x86_64 (64-bit)
Graphics Platform: Wayland

**Comment by zefr0x** [comment]
It looks like Plasma's notification demon accept minimum of one second between notification update:
https://invent.kde.org/plasma/plasma-workspace/-/blob/8686d07dabdef1d5f2a24cce05a5ecd044430ab1/libnotificationmanager/server_p.cpp#L218

Ianny sends an update directly after creating the notification to create the progress bar.

I will add a delay between those operations in the next release.

**Comment by kofm** [comment]
Thank you!!

**Comment by kofm** [comment]
It works perfectly! Thank you very much.
(I don't see any progress bar though on KDE)
