### ISSUE TITLE
What is the meaning and usage of the idle_timeout config item?

### ISSUE THREAD

**Issue by tonyho** [zer0-x/ianny#6]
Personally, I don't understand the meaning of the `idle_timeout` items in the content of the config.toml, could you kindly to explain it thanks.

```
[timer]
idle_timeout = 240
short_break_timeout = 1200
long_break_timeout = 2700
short_break_duration = 120
long_break_duration = 240

[notification]
show_progress_bar = true
minimum_update_delay = 1

```

**Comment by zefr0x** [comment]
When you are idle (not using the computer) for `idle_timeout` seconds, the timer will stop and reset.

Use case:
When you are away from your computer you basically toke a break so no need to take another break in a short time.
